$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'

# Список кастомных словарей
dictionaryDefinitions:
  - name: wormhole-dictionary
    path: './cspell-custom-words.txt'  # Путь к файлу кастомных слов
    addWords: true  # Добавление слов из кастомного файла в основной словарь

# Используемые словари
dictionaries:
  - wormhole-dictionary  # Добавляем кастомный словарь

# Пути, которые нужно игнорировать при проверке орфографии
ignorePaths:
  # Игнорирование go-модулей для guardian node
  - '/pkg/mod/**'
  # Игнорирование node_modules (для зависимостей Node.js)
  - '**/node_modules/**'
  # Игнорирование файла с кастомными словами
  - '**/requirements.txt'
  - '/cspell-custom-words.txt'
  # Игнорирование расширений tilt
  - '/tilt_modules/**'
  # Игнорирование сборочных артефактов
  - '/clients/js/build/**'
  - '/wormchain/build/**'
  # Игнорирование генерируемых файлов cosmos* и cosmwasm*
  - '/wormchain/ts-sdk/src/modules/cosm.*/**'
  - '/wormchain/ts-sdk/src/modules/osmosis*/**'

# Можно добавить дополнительные настройки для интеграции с другими инструментами
# Например, можно указать дополнительные файлы или пути для добавления в словарь
# или настроить дополнительные правила для игнорирования распространённых ошибок.
