const fs = require('fs');
const WebSocket = require('ws');

async function listenBtc() {
    // Load the certificate for the TLS connection which is automatically
    // generated by btcd when it starts the RPC server and doesn't already
    // have one.
//    var cert = fs.readFileSync('/path/to/btcd/appdata/rpc.cert');
    var user = "wormhole";
    var password = "w0rmh013";

    // Initiate the websocket connection.  The btcd generated certificate acts as
    // its own certificate authority, so it needs to be specified in the 'ca' array
    // for the certificate to properly validate.
    var ws = new WebSocket('wss://127.0.0.1:18556/ws', {
        headers: {
            'Authorization': 'Basic '+new Buffer(user+':'+password).toString('base64')
        },
        //  cert: cert,
        //  ca: [cert]
    });
    ws.on('open', function() {
        console.log('CONNECTED');
        // Send a JSON-RPC command to be notified when blocks are connected and
        // disconnected from the chain.
        ws.send('{"jsonrpc":"1.0","id":"0","method":"notifyblocks","params":[]}');
    });
    ws.on('message', function(data  : any, flags : any) {
        console.log(data);
    });
    ws.on('error', function(derp : any) {
        console.log('ERROR:' + derp);
    })
    ws.on('close', function(data : any) {
        console.log('DISCONNECTED');
    })

    console.log("test complete");
}

listenBtc();
