#!/bin/bash
set -uo pipefail

modules=(TokenBridge)
network=testnet
chains=$(worm evm chains)


for module in ${modules[@]}; do
  for chain in ${chains[@]}; do
    ./upgrade "$network" "$module" "$chain"
  done
done
